# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:14

pipelines:
  default:
      - step:
          name: Empty step
          script:
            - echo "Empty"
      - step:
          name: Deploy to production
          deployment: production
          trigger: manual  # Uncomment to make this a manual deployment.
          caches:
            - node
          script:
            - echo "Deploying to production environment"
            - yarn install
            - yarn build
            - export BUILD_FILE="start.playjammy_com_${BITBUCKET_COMMIT}_$BITBUCKET_BUILD_NUMBER.tar.gz"
            - echo $BUILD_FILE
            - tar czf $BUILD_FILE .next node_modules public package.json
            - (umask  077 ; echo $SSH_PRODUCTION_PRIVATE_KEY | base64 --decode > www.key)
            - chmod 600 www.key
            - scp -i www.key $BUILD_FILE $PRODUCTION_USER@$PRODUCTION_SERVER:/tmp/
            - ssh -i www.key $PRODUCTION_USER@$PRODUCTION_SERVER "find $PRODUCTION_PATH -mindepth 1 -delete && cd $PRODUCTION_PATH && tar -xzf /tmp/$BUILD_FILE && rm /tmp/$BUILD_FILE && pm2 restart nextjs"
            - >-
              curl -X POST -H 'Content-type: application/json' --data '{"text":":zap: [START.PJ] Commit *'"${BITBUCKET_COMMIT:0:8}"'* was deployed to *'"${PRODUCTION_URL}"'*!"}' $SLACK_WEBHOOK_URL
